sudo: required

services:
  - docker

env:
  global:
    - VERSION=2018-04-22a
    - GITHUB_REPO=crazy-max/docker-dokuwiki
    - DOCKER_USERNAME=crazymax
    - DOCKER_REPONAME=dokuwiki
    - QUAY_USERNAME=crazymax
    - QUAY_REPONAME=dokuwiki
    - MICROBADGER_HOOK=https://hooks.microbadger.com/images/crazymax/dokuwiki/cHV4g-ZhqTyuLtWXo9_4Mr1TNcE=
    - secure: icgx67zegohE1xYguBsNvHof0RvZKH6PUFnqEdhbjUIJRFoqk8G4eHtU6jUbV6bEm3j9AWd5BA9x//J5XHRzGRu/VNceB92SZHrGWSac4m7hguARN0ZeEKL09bp6b99/SqKZFnRk+fCx2Vm4vP/4lN12VtWnlfyFI6zg135n9T2I7Yd2c5vXCZDrNAodJ/Sl8l7t78gYe0DNhMwbZe55nLDcm6gh50BbmFODJxOECJPYw47k8uzR8blrzrwemYiLPhCSRjlbd15Wk6Fpqv5m6cUBY6dc6fdvZcPs8+pKAvXgM7ybDdgMfBBYrJ1h9JMlQCrQw3cZLFwj/hfEJB6hqZgy8ecJDjjHxyzxXSgha38Jkidq7fCNnGile4SguH2kxUyg4UY6Cn0gU2XH1hGmImaMpGadCmQ/8h/gcyT3n6HLgaA2o8wBuybX97nYmWasUm6ZXJEbz2OlBhvP6MQMkvEr8sJX1OHk7XW+LHYjrTJo4EjxptGtZuJx/9RRgxiWbSZcbxrhkC/NcZLrES3O3jvZJM+yI0XFH/qAKIPPcNdqCI0/GJaoE1KWOj5LAvgJiaU817aZI2bZdB+VBFqrnftNCB5Mk8VCaasXSsxNarR3WSrNYY/H0y6QD4xfaNfSaFRYPz9VHCDIt7gEyR77iMjEtBONUhp7VS+0JdOxtvo= # DOCKER_PASSWORD
    - secure: BUKbxckdrC1HciBcZlMh9YgqRHakV+El5zzpwoXsz+ia9CRWBFPkxxpRlo1nZ8q181Zxs4n4tEHHl/d1dQBA5mh+BrkTV9SF88eVRkDUEWqA7+zXiuzh2gh81qbeW5GoGT1RYy1U8pHHET9Tgvy61a/V7GfLB5N//zCZrsBNuLY5oZ85itJLfl34PTxQUBDbUgpWMW3j7kxSpgx6d3/TSDsxYoke3WxdByMG95HFvCO2a3b084z45uiJLTRKZxj/NSvY6FPjk6jbqPl+9gRxl2AFlJQdo3yTKNJFR7SF/ef95dlwznOJ3FQU0DX+HlO81Bo4lSDELvqrnue3K+lx16eic2zQNg88cKmuYNQxLq6gex667FGPqDnJo4lgi1wXlZLrC9lmTgYBQTXf7sD0yI0IcMnpE1QA7Jvfcb+d/WXoNg/n9m33UI7xC8Q843OT+WIu/gxpnDvTJOiP/60vvnsaDpDKDcvrOaMAdalesGUMivUGtbzoqrtkxisHlXUORrM//ii431oqz3bQ0ypXs7V4ahao914hBSiltQsCBSumJGa73YiJjphS4SWX7nFkDeJMRiBBxn6mpUduEDQ3SesAGOSST91ki5t1jRBzCQex/y6ERluw1aVGbEv7kCeRNk9SUXj8GpYHSyPfvGqYqP1kIqzcg5kQUyW9OHEWiqs= # QUAY_PASSWORD
    - secure: NxEgKmrVsyLqDaMTGhWTpuXPkYTCNc7lpjWYZB/inQqPT2ggY0Kh+RF4uI75g8CbuSZpUvEnd5rDDQOH8nNJkpM5702EEj82UgxhAJwJSfN2ctkODd7dsLBCcQ1t/QBExEu+2YVrEjyeiX9F0kryNoEF3V+h9Ai6nYcKM1SPp8M8CilRpllzG057MbPuP4j04sL7UKegoA3yzVjMJV/2zkGUbMjUouOTskRoTV5qo+IMk/chnQ7qtk0Zxd/eN0QXW5OTYj7cGC2qhburqMW+JXEPsdt2VECCbEQo8qnW/qmnaO8DFVckxBPK7H4ioUxbzd8SFtGwM1cx7MCMCSFkUkJa/Cp/WZ6xF4WvY5OcByvQvfEhk/L9SNPQLFjdNtSIMp+jim8XwKDdcq8I2dm/iQdpoP26pWkp9254fqJlfWrFfi6u4QViK9X6cuLgGR/BaKhFD5aFOtoT0KLeSs+B/9HMHE5zFgz396wLmWvenNfPEb/fUZhSuc4Ql5sCdq5eqJz2KDipbtVOig3EkuiM7Ngc5h4sGI62oebP2HQGTWP48BuqtOtppozBEMtSqnHSP55bao9/xneqwDHV+/KBzQGKlib4Vky9JEv9lDVOBBw9uF9ahH3duhvH/7C2BiGjtgnr+Y8HSEd3NO0yeCDtikbK+NvskdhHJbU1ogs4A7I= # GITHUB_TOKEN

before_install:
  - sudo apt-get update
  - docker --version
  - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
  - export DOCKER_TAG=$(if [ "$BRANCH" == "master" ]; then echo "latest"; else echo $BRANCH; fi)
  - echo "TRAVIS_BRANCH=$TRAVIS_BRANCH, PR=$PR, BRANCH=$BRANCH, DOCKER_TAG=$DOCKER_TAG"

install:
  - |
    docker build --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` \
    --build-arg VCS_REF=${TRAVIS_COMMIT::8} \
    --build-arg VERSION=${VERSION} \
    -t docker_build .

before_script:
  - docker run -d --name $DOCKER_REPONAME docker_build
  - sleep 5
  - docker logs $DOCKER_REPONAME

script:
  - docker ps | grep $DOCKER_REPONAME
  - |
    test $TRAVIS_PULL_REQUEST = false \
    && echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin \
    && docker tag docker_build $DOCKER_USERNAME/$DOCKER_REPONAME:$DOCKER_TAG \
    && docker tag docker_build $DOCKER_USERNAME/$DOCKER_REPONAME:$VERSION \
    && docker push $DOCKER_USERNAME/$DOCKER_REPONAME \
    && curl -X POST $MICROBADGER_HOOK \
    && echo "$QUAY_PASSWORD" | docker login quay.io --username "$QUAY_USERNAME" --password-stdin \
    && docker tag docker_build quay.io/$DOCKER_USERNAME/$DOCKER_REPONAME:$DOCKER_TAG \
    && docker tag docker_build quay.io/$DOCKER_USERNAME/$DOCKER_REPONAME:$VERSION \
    && docker push quay.io/$QUAY_USERNAME/$QUAY_REPONAME

branches:
  except:
    - /^[0-9]/

notifications:
  webhooks:
    secure: SRYk4TSvUHARlVE5pu08ARuC/TpTxsJMlUrDeEVlW+kGP0vF6G75x5jI0rLDZ04ttzboYuIcoFc34vTF2p4W8FUJlXmyTiND5vSDT1PjvfLggU6YP2EsyPX1qJSyawsmnqtUOa8QbwJMyTwzeurT/F7dKlyXkS+XfjJPOBOQMGWx7DxfWKF7UlusQgpc0nacsPdoziR+4Pcrm33HMZ3RYpQHC4xTKR88/5AlXdcAiuYIXJyjb5329ebwxdK2ja4EV+PLc8E8cDpNULcXCORHaN4aHSEJS5EfUs44ATnrnt7yPlzxiZhtwSfBhjRFxPQD6J+wSNVoEGJWCm/q5JT1WrU9/L7EJIHqKFldBDm5oewiDD+wa3Os35O2gSDi61alf4r8DkUtVYs96iD8FULPU7dnR8/a4SLujTVPMgc31BzkxFP629wP4wew8QR8bJdgojBhf/RpRWJymZzVEpCV378m1AeWhpgWJ/fTyHDDAKJ2JDmVHE+vm15PcihVb79KARRg4gruazhLosr/6e3BGDTzqstcUItS0pmGHRAvyRqmMQDbo09lnHkjP5UyS+3hwZxsMyt4mZLsRA1EpU3iC1TvjOrliTpiIJ4vEQnYvHknqxGegj0lcFkY5myu54mSrJlZJWSraC62AhvwACLBzW1ojMd9DW83u10uqDjTv64=
