version: "3.5"

services:
  dokuwiki:
    image: crazymax/dokuwiki:latest
    container_name: dokuwiki
    ports:
      - target: 8000
        published: 8000
        protocol: tcp
    volumes:
      - "./data:/data"
    env_file:
      - "./dokuwiki.env"
    restart: always
